//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelera
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipios
    {
        public int ID { get; set; }
        public string Letra { get; set; }
        public string Municipio { get; set; }
        public string Code { get; set; }
    }
}
