//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelera
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peliculas
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Director { get; set; }
        public string Productor { get; set; }
        public string Clasificacion { get; set; }
        public Nullable<System.TimeSpan> Duracion { get; set; }
        public string Genero { get; set; }
    }
}
